export const data: any = [
  {
    id: 1,
    title: "Family House for rent",
    description: "some thing that help in seo", // this description is post as a content in our facebook and instragarm page so you have to write properly
    purpose: "For Rent",
    categories: "real-state",
    subcategories: "House",
    type: "Family House",
    images: [],
    displayImage: "/images/house.jpg",
    area: "4 aana",
    features: ["4 bike parking", "2 car parking", "garden"],
    tage: ["Horseforrent", "affodable", "Nearbuspark", "notisefree"],
    price: 30000,
    displayPrice: 28000,
    isActive: true,
    isNegociated: false,
    isPublic: true,
    isFeatures: true,
    numberOfView: 100,
    createdAt: new Date(),
    updatedAt: new Date(),
    location: {
      lat: 27.734571,
      long: 85.303543,
    },
    address: "Macchapokhari",
    district: "districtId",
    province: "provinceId",
    city: "citiid",
    addedBy: "userid",
  },
  {
    id: 2,
    title: "Family House for rent",
    description: "some thing that help in seo",
    purpose: "For Rent",
    categories: "real-state",
    subcategories: "House",
    type: "Family House",
    images: [],
    displayImage: "/images/house.jpg",
    area: "4 aana",
    features: ["4 bike parking", "2 car parking", "garden"],
    price: 30000, //if you dont want to display discount dont add here
    tage: ["Horseforrent", "affodable", "Nearbuspark", "notisefree"],
    displayPrice: 28000,
    isActive: true,
    isNegociated: true,
    isPublic: true,
    isFeatures: true,
    numberOfView: 100,
    createdAt: new Date(),
    updatedAt: new Date(),
    location: {
      lat: 27.734571,
      long: 85.303543,
    },
    address: "Macchapokhari",
    district: "districtId",
    province: "provinceId",
    city: "citiid",
    addedBy: "userid",
  },
];

export const slideImage: any = [
  {
    id: 1,
    image: "/images/house.jpg",
    url: "",
  },
  {
    id: 2,
    image: "/images/house1.jpg",
    url: "",
  },
  {
    id: 3,
    image: "/images/house2.jpg",
    url: "",
  },
  {
    id: 4,
    image: "/images/house3.jpg",
    url: "",
  },
  {
    id: 5,
    image: "/images/house4.jpg",
    url: "",
  },
  {
    id: 6,
    image: "/images/house5.jpg",
    url: "",
  },
];
